--- 
- hosts: all
  become: yes 
  tasks: 
    - name: i want to install wget
      apt:
         name: wget
         state: present 

    - name: i want to install apache2
      apt:
         name: apache2
         state: present